filter:
    excluded_paths:
        - 'tests/*'
        - 'examples/*'
tools:
    php_sim:
        min_mass: 30
checks:
    php:
        duplication: false
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=log/coverage.xml'
                coverage:
                    file: 'log/coverage.xml'
                    format: 'clover'
    environment:
        mysql: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
